[build-system]
requires = ["setuptools", "toml"]
build-backend = "setuptools.build_meta"

[project]
name = "z-omni-logger"
version = "1.3.0"
authors = [{ name = "Mhd Zeid Mahfouz", email = "mhd.zeid.mahfouz@gmail.com" }]
description = "A pre-configured Python logging package with customizable handlers and configuration."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "colorama",
    "requests",
    "dynaconf>=3.2.4",
    "pathlib",
    "datetime",
    "toml",
    "platformdirs",
]

[project.urls]
Homepage = "https://github.com/Zeid-M/omni_logger"
Issues = "https://github.com/Zeid-M/omni_logger/issues"

[tool.setuptools.package-data]

"omni_logger.config.config_templates" = ["*", ".*"]
"omni_logger.config.config_files" = ["default_logger_settings.toml"]

[project.scripts]
omni_logger_install_custom_configuration = "omni_logger.helper_scripts.config_installer:main"
